### ISSUE TITLE
Criar horário

### ISSUE THREAD

**Issue by egewarth** [Dulce-Work-Schedule/2018.1-Dulce_Schedule#1]
Eu, como gestor, desejo criar um horário de um plantonista, a fim de, organizar os horarios dos plantonistas.

Critérios de aceitação:
- Criar um horário
- Um horário estar em um dia/mês/ano válido.
- Um horário só poderá ser criado se a quantidade máxima de horas do mês não for ultrapassada.
- Um horário só poderá ser criado se a quantidade máxima de horas da semana não for ultrapassada.
- Um horário deve pertencer a apenas um plantonista.
- Um plantonista pode possuir apenas um plantão por horário (conflito de horários).

Atributos:
- [x] Data Início
- [x] Data Fim
- [x] Horário Início
- [x] Horário Fim
- [x] Setor
- [x] Plantonista

Validações:
- [x] O início do plantão deve ser antes do fim do plantão
- [x] Não deve ultrapassar a quantidade máxima de horas definida
- [x] Deve ser informado um plantonista válido
- [x] Deve ser informado um setor válido
- [x] Deve ser informado um setor com o qual o plantonista esteja relacionado
